version: '3.9'

services:
  web:
    build: .
    ports:
      - 3003:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
